### ISSUE TITLE
Replace the placeholder GOV.UK favicons with HMCTS assets

### ISSUE THREAD

**Issue by duncancrawford** [hmcts/hmcts.github.io#625]
## What's there now, and why

`govuk_tech_docs` 6 renders favicon links in its core layout, branching on `show_govuk_logo`. This
site sets that to **false**, so the layout takes the branch expecting the site to supply its own:

```
<link rel="icon" sizes="48x48" href="/images/favicon.ico">
<link rel="icon" sizes="any" href="/images/favicon.svg" type="image/svg+xml">
```

Version 3 of the gem referenced no favicon at all, so this repository never needed one. On the
upgrade (#624) every page linked two files that did not exist — 218 broken references, one pair per
page.

To unblock that PR the files were filled with **GOV.UK Frontend's own favicons**, copied from the
gem, because the repository has no HMCTS icon assets of its own.

## Why that needs replacing

It puts the **GOV.UK crown on a site that deliberately turns GOV.UK branding off**. `show_govuk_logo:
false` is a considered setting — this is an HMCTS engineering documentation site, not a GOV.UK
service — and the favicon now contradicts it. GOV.UK brand assets are also not intended for use
outside GOV.UK services.

It is not a functional problem. Nothing is broken and no page fails. It is the wrong mark in the
browser tab.

## Two ways to resolve it — someone with the brand context should choose

**1. Supply HMCTS favicons** (expected route). Replace two files:

- `source/images/favicon.ico` — 48×48, ideally multi-resolution
- `source/images/favicon.svg` — scalable, for `sizes="any"`

Nothing in the code or config reads their contents, so this is a straight file swap.

**2. Or decide the site *should* be GOV.UK-branded** and set `show_govuk_logo: true` in
`config/tech-docs.yml`. The layout then uses the gem's bundled GOV.UK icons from its own asset path,
legitimately, and the two files here can be deleted. This also changes the visible page header, so it
is a bigger decision than it looks.

## Acceptance

- `source/images/favicon.*` carry HMCTS branding, **or** option 2 is taken and the placeholder files
  removed
- `bundle exec middleman build`, `rake check_pages` and `rake check_urls` all still pass — the link
  check is what caught the original gap, so it is the regression test
- No other file changes

## Context

- Introduced by #624 (gem update to `govuk_tech_docs` 6.3.0)
- Flagged in that PR and in the commit message rather than left silent, because it is a branding
  decision rather than an engineering one

**Comment by duncancrawford** [comment]
## Add `opengraph-image.png` too

The gem's upgrade notes list three assets together, not two — [alphagov/tech-docs-gem#387](https://github.com/alphagov/tech-docs-gem/pull/387):

> add `favicon.ico`, `favicon.svg` and `opengraph-image.png` to your `source/images` folder
> set `show_govuk_logo: false`

I only added the two favicons in #624, so `source/images/opengraph-image.png` is still absent.

**It is not breaking anything today.** The built pages carry no `og:image` meta tag, so nothing links a missing file and the link check passes legitimately rather than by luck. The effect is that social and chat previews of these pages have no image.

Same owner and same decision as the favicons, so worth doing in one go: an HMCTS-branded image at `source/images/opengraph-image.png`. Recommended size for Open Graph is 1200×630.

**Correction to this issue's framing:** I originally described these as assets the gem expects without saying so. That was wrong — both the favicons and the JavaScript entry point are documented breaking changes in the gem's CHANGELOG. The repository had been pinned to `govuk_tech_docs` 3.3.1 since before those changes, so the requirements arrived all at once on the upgrade. The gap is drift, not missing documentation.
